include: package:pedantic/analysis_options.1.11.0.yaml
linter:
  rules:
    - public_member_api_docs
analyzer:
  exclude: [lib/generated/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    public_member_api_docs: ignore