name: slide_popup_dialog
description: Popup dialog with slide mechanism. Use it like AlertDialog or SimpleDialog.
version: 0.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0